### PR TITLE
added cython stuff

### PR DESCRIPTION
**Pull request by zerothi**

### CODE REVIEW

**Comment by zerothi** [comment]
try this, it should be more comparable with sisl method (and includes Cython code)

**Comment by zerothi** [comment]
Now to check do this:
```bash
python3 -c 'from package1 import * ; hello_world() ; print_csources()'
```

**Comment by kovalp** [comment]
```
(py37-pyside2) kovalp:~$ python3 -c 'from package1 import * ; hello_world() ; print_csources()'
 from fortran
from Cython

```

Under Linux works.

**Comment by zerothi** [comment]
great!

**Comment by kovalp** [comment]
Under Windows

The package1 is compiled
[pip.out.txt](https://github.com/kovalp/sisl_approach_f2py/files/5001296/pip.out.txt)

Note, the Visual Studio's C/C++ is still not used. 

```
$ python -c 'from package1 import * ; hello_world() ; print_csources()'
 from fortran
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'print_csources' is not defined

```
i.e. cython part is not compiled.

I was using again 
`
$ pip install -vvv --no-cache-dir --no-deps --no-index --no-build-isolation --compile --global-option build --global-option --compiler=mingw32 --global-option --fcompiler=gnu95 . &> pip.out.txt`

**Comment by zerothi** [comment]
But this is a very different problem than with sisl.

In sisl [here](https://github.com/zerothi/sisl/issues/244#issuecomment-665591223) the problem is a fortran source. Since Cython sources are imported prior to this line of code, then I am sure that Cython sources are imported prior.

However, here you have problems with the Cython sources...

I really have no clue what is going wrong... Windows is not easy it seems.

**Comment by zerothi** [comment]
Note that in this code you are using mingw32 compiler, whereas in the link i provided you were still using msvcc compiler. So clearly there are somethings not working and the clash of everything seems to be the problem...

**Comment by kovalp** [comment]
I also commented that sisl uses the visual studio compilers, while
sisl_approach_f2py uses gcc. However, I have been using the same pip
command in both cases.

1. I don't understand why the cython function does not exist in the
installed version of sisl_approach_f2py.

2. I don't understand why sisl disobeys the --compilator option.

Peter

**Comment by kovalp** [comment]
Pip/setuptools are not easy either.

**Comment by zerothi** [comment]
You could try with the regular `setup.py` method and see where this goes.

Then it should could be a bit easier to check
```
python3 setup.py build --compiler=mingw32 --fcompiler=gnu95`
```


Oh, one last thing. Are you doing `python -c '...'` in the same directory as the package? That will never work ;)

You have to be in a directory where there is no `package1` directory! Same goes for `sisl`? Is this perhaps the cause?

**Comment by kovalp** [comment]
I am stepping out of the souce directory.

**Comment by zerothi** [comment]
> I am stepping out of the souce directory.

hmm... :(

**Comment by kovalp** [comment]
I think playing with plain setuptools gives another clue. Below is the command log of what I did. In human language, I uninstalled package1 (using pip uninstall); removed build/, dist/ and package1.egg-info from the sources; executed python setup.py *build*, then *install*, stepped out of the sources and run the probe command.

```
$ pip uninstall package1
Found existing installation: package1 1.0
Uninstalling package1-1.0:
  Would remove:
    c:\users\koval\appdata\local\programs\python\python37\lib\site-packages\package1-1.0-py3.7-win-amd64.egg
Proceed (y/n)? y
  Successfully uninstalled package1-1.0

koval@DESKTOP-B5CLTB9 MINGW64 ~
$ cd -
/c/Users/koval/programs/sisl_approach_f2py

koval@DESKTOP-B5CLTB9 MINGW64 ~/programs/sisl_approach_f2py (master)
$ ls
build/  dist/  package1/  package1.egg-info/  pip.out.txt  README.md  setup.py*

koval@DESKTOP-B5CLTB9 MINGW64 ~/programs/sisl_approach_f2py (master)
$ rm -rf build/ dist/ package1.egg-info/

koval@DESKTOP-B5CLTB9 MINGW64 ~/programs/sisl_approach_f2py (master)
$ python setup.py build --compiler=mingw32 --fcompiler=gfortran &>setup.build.out.txt

koval@DESKTOP-B5CLTB9 MINGW64 ~/programs/sisl_approach_f2py (master)
$ python setup.py install &>setup.install.out.txt

koval@DESKTOP-B5CLTB9 MINGW64 ~/programs/sisl_approach_f2py (master)
$ cd

koval@DESKTOP-B5CLTB9 MINGW64 ~
$ python -c 'from package1 import *; hello_world() ; print_csources()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\koval\AppData\Local\Programs\Python\Python37\lib\site-packages\package1-1.0-py3.7-win-amd64.egg\package1\__init__.py", line 1, in <module>
    from ._sources import hello_world
ImportError: DLL load failed: The specified module could not be found.

koval@DESKTOP-B5CLTB9 MINGW64 ~
```
[setup.build.out.txt](https://github.com/kovalp/sisl_approach_f2py/files/5001831/setup.build.out.txt)

[setup.install.out.txt](https://github.com/kovalp/sisl_approach_f2py/files/5001832/setup.install.out.txt)

Observations:
1. gcc compiler is used in the build step;
2. mvscc (!) compiler is used in the install step;
3. the installation of package1 is invalid similar to installing sisl.

So, there are inconsistencies/ out of control things happen between build/install in setuptools and between setuptools and pip.

I will keep looking.

**Comment by zerothi** [comment]
Ok, so we are getting closer, I found this which perhaps could be a workaround https://stackoverflow.com/q/33331563

**Comment by kovalp** [comment]
I added setup.cfg with the section [build] and entries compiler=mingw32, fcompiler=gfortran and violá
```

koval@DESKTOP-B5CLTB9 MINGW64 ~
$ python -c 'from package1 import *; hello_world() ; print_csources()'
 from fortran
from Cython
```

**Comment by zerothi** [comment]
Great!

**Pull request merged**
